name: BKTree_Build_And_Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install CMake
      run: |
        sudo apt-get update -y
        sudo apt-get install cmake -y
        cmake --version

    - name: Build and Test
      run: |
        mkdir -p build
        cd ./build
        cmake ..
        make
        ./output
